@extends('layouts.administracion')
@section('titulo', 'Características')
@section('contenido')
    <header class="features-heading"><div><p class="features-heading__eyebrow">Configuración</p><h1>Características</h1><p>Definí los servicios, ambientes, amenities y opciones disponibles para tus propiedades.</p></div><a href="{{ route('administracion.caracteristicas.crear') }}" class="features-create-action">Nueva característica</a></header>
    <section class="features-list-card">
        <header class="features-list-card__header"><div><h2>Características disponibles</h2><p>Organizalas por categoría y activá solo las que usás en tus publicaciones.</p></div><p class="features-list-card__count">{{ $caracteristicas->total() }} {{ Str::plural('característica', $caracteristicas->total()) }}</p></header>
        <form method="GET" action="{{ route('administracion.caracteristicas.listar') }}" class="features-filters">
            <label class="features-search"><span>Buscar</span><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input name="buscar" value="{{ $busqueda }}" placeholder="Buscar por nombre" aria-label="Buscar característica"></label>
            <label class="features-select-filter"><span>Categoría</span><select name="categoria" aria-label="Filtrar por categoría"><option value="">Todas las categorías</option>@foreach ($categorias as $categoria)<option value="{{ $categoria->value }}" @selected($categoriaSeleccionada === $categoria->value)>{{ $categoria->etiqueta() }}</option>@endforeach</select></label>
            <label class="features-select-filter"><span>Estado</span><select name="estado" aria-label="Filtrar por estado"><option value="todas">Todas</option><option value="activas" @selected($estado === 'activas')>Activas</option><option value="inactivas" @selected($estado === 'inactivas')>Inactivas</option></select></label>
            <div class="features-filter-actions"><button>Aplicar</button>@if ($busqueda !== '' || $categoriaSeleccionada || $estado !== 'todas')<a href="{{ route('administracion.caracteristicas.listar') }}">Limpiar</a>@endif</div>
        </form>
        <div class="features-table-wrap"><table class="features-table"><thead><tr><th>Nombre</th><th>Categoría</th><th>Estado</th><th class="text-right">Acciones</th></tr></thead><tbody>@forelse ($caracteristicas as $caracteristica)<tr><td><strong>{{ $caracteristica->nombre }}</strong></td><td><span class="features-category">{{ $caracteristica->categoria->etiqueta() }}</span></td><td><span @class(['features-status', 'is-active' => $caracteristica->activa, 'is-inactive' => ! $caracteristica->activa])><i></i>{{ $caracteristica->activa ? 'Activa' : 'Inactiva' }}</span></td><td class="text-right"><div class="features-row-actions"><a href="{{ route('administracion.caracteristicas.editar', $caracteristica) }}">Editar</a><form method="POST" action="{{ route('administracion.caracteristicas.cambiar-estado', $caracteristica) }}">@csrf @method('PATCH')<button>{{ $caracteristica->activa ? 'Desactivar' : 'Activar' }}</button></form></div></td></tr>@empty<tr><td colspan="4" class="features-empty">No se encontraron características con estos filtros.</td></tr>@endforelse</tbody></table></div>
        @if ($caracteristicas->hasPages())<footer class="features-pagination">{{ $caracteristicas->links() }}</footer>@endif
    </section>
@endsection
